name: Code audit

on: [push, pull_request]

jobs:
  audit:
    name: Code audit
    runs-on: ubuntu-latest
    steps:
      - name: â¬‡ Git checkout
        uses: actions/checkout@v4
      # - name: âš™ï¸ Setup Node
      #   uses: actions/setup-node@v3
      #   with:
      #     node-version: latest
      - name: ğŸ’¾ Install modules
        run: npm ci
      - name: ğŸ” Lint
        run: npx eslint --max-warnings 1